version: '3'

services:
  web:
    build: .
    # command: poetry run gunicorn --bind 0.0.0.0:8000 src.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - webservice
    environment:
      - DJANGO_ENVIRONMENT=development
      - DB_PASSWORD=myproject_password
      - DB_NAME=myproject_db
      - DB_USER =myproject_user
      - DB_HOST=db
      - DB_PORT= 5432
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - webservice
    environment:
      - POSTGRES_DB=myproject_db
      - POSTGRES_USER=myproject_user
      - POSTGRES_PASSWORD=myproject_password

networks:
  # The presence of these objects is sufficient to define them
  webservice: {}