version: '3'

services:
  web:
    build: .
    command: poetry run gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/src/staticfiles
      - media_volume:/src/mediafiles
    ports:
      - "8001:8000"
    networks:
      - webservice
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - webservice
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/src/staticfiles
      - media_volume:/src/mediafiles
    ports:
      - "8000:8000"
    depends_on:
      - web
    networks:
      - webservice

networks:
  # The presence of these objects is sufficient to define them
  webservice: { }

volumes:
  postgres_data:
  static_volume:
  media_volume: