version: '3'

services:
  web:
    build: .
    command: poetry run gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/src/staticfiles
      - media_volume:/src/mediafiles
    ports:
      - "8000:8000"
    networks:
      - webservice
    environment:
      - DJANGO_ENVIRONMENT=development
      - DB_PASSWORD=myproject_password181
      - DB_NAME=myproject_db
      - DB_USER =postgres
      - DB_HOST=db
      - DB_PORT= 5432
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - webservice
    environment:
      - POSTGRES_DB=myproject_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=myproject_password181
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/src/staticfiles
      - media_volume:/src/mediafiles
    ports:
      - "1337:80"
    depends_on:
      - web
    networks:
      - webservice

networks:
  # The presence of these objects is sufficient to define them
  webservice: { }

volumes:
  postgres_data:
  static_volume:
  media_volume: