# Generated by Django 4.1.7 on 2023-02-27 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mastertrader',
            old_name='trader_id',
            new_name='external_trader_id',
        ),
    ]
