# Generated by Django 4.1.7 on 2023-02-27 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_trader_id_mastertrader_external_trader_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mastertrader',
            unique_together={('external_trader_id', 'source')},
        ),
    ]
