# Generated by Django 4.1.7 on 2023-02-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterTrader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trader_id', models.CharField(max_length=60)),
                ('source', models.CharField(max_length=60)),
                ('signals', models.JSONField()),
            ],
        ),
    ]
