# Generated by Django 4.1.7 on 2023-03-19 23:02

import datetime
from django.db import migrations, models

from django.utils import timezone


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawlrunner",
            name="last_seen_at",
            field=models.DateTimeField(
                default=datetime.datetime.now(tz=timezone.utc)
            ),
            preserve_default=False,
        ),
    ]
