# Generated by Django 4.1.7 on 2023-03-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_crawlrunner_last_seen_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crawlertype",
            name="source",
            field=models.CharField(
                choices=[("zulu", "Zulu Trade"), ("exness", "Exness Trade")],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="mastertrader",
            name="source",
            field=models.CharField(
                choices=[("zulu", "Zulu Trade"), ("exness", "Exness Trade")],
                max_length=255,
            ),
        ),
    ]
