# Generated by Django 4.1.7 on 2023-03-10 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_mastertrader_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrawlerType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("source", models.CharField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="mastertrader",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="mastertrader",
            name="name",
            field=models.CharField(default="zulu_trade", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mastertrader",
            name="source",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="CrawlRunner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "crawler_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.crawlertype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CrawlAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crawl_runner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.crawlrunner",
                    ),
                ),
                (
                    "master_trader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.mastertrader",
                    ),
                ),
            ],
        ),
    ]
