# Generated by Django 4.1.7 on 2023-03-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_crawlertype_source_alter_mastertrader_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signal",
            name="market_price",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="signal",
            name="stop_loss",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="signal",
            name="symbol",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="signal",
            name="take_profit",
            field=models.FloatField(null=True),
        ),
    ]
