# Generated by Django 4.1.7 on 2023-03-12 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_crawlertype_mastertrader_is_active_mastertrader_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastertrader',
            name='signals',
        ),
        migrations.AlterField(
            model_name='crawlertype',
            name='source',
            field=models.CharField(choices=[('zulu', 'Zulu Trade')], max_length=255),
        ),
        migrations.AlterField(
            model_name='mastertrader',
            name='name',
            field=models.CharField(default='default_name', max_length=255),
        ),
        migrations.AlterField(
            model_name='mastertrader',
            name='source',
            field=models.CharField(choices=[('zulu', 'Zulu Trade')], max_length=255),
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_signal_id', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('size', models.FloatField()),
                ('time', models.DateTimeField()),
                ('price_order', models.FloatField()),
                ('stop_loss', models.FloatField()),
                ('take_profit', models.FloatField()),
                ('market_price', models.FloatField()),
                ('limit', models.FloatField()),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='api.mastertrader')),
            ],
            options={
                'unique_together': {('trader_id', 'external_signal_id')},
            },
        ),
    ]
