# Generated by Django 4.1.7 on 2023-03-12 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_mastertrader_signals_alter_crawlertype_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal',
            name='limit',
        ),
    ]
