# Generated by Django 4.1.7 on 2023-03-13 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_signal_unique_together_remove_crawlertype_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crawlassignment",
            name="crawl_runner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="api.crawlrunner",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="signal",
            unique_together={("trader", "external_signal_id")},
        ),
    ]
